<?php

namespace EmauxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HomepageSectionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomepageSectionsRepository extends EntityRepository
{
}
